In [ ]:
# pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# pip install numpy   

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('insurance_data.csv')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   gender    1338 non-null   str    
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   str    
 5   region    1338 non-null   str    
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB


In [7]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830
1334,18,female,31.920,0,no,northeast,2205.98080
1335,18,female,36.850,0,no,southeast,1629.83350
1336,21,female,25.800,0,no,southwest,2007.94500


In [8]:
df[['gender']]

,gender
0,female
1,male
2,male
3,male
4,male
...,...
1333,male
1334,female
1335,female
1336,female


In [9]:
df['gender'].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [10]:
df['children'].unique()

array([0, 1, 3, 2, 5, 4])

In [11]:
df['gender'].value_counts()

gender
male      676
female    662
Name: count, dtype: int64

In [12]:
gender_dict={
    'female':1, 'male':2
}

In [13]:
df['gender']=df['gender'].map(gender_dict)

In [14]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,1,27.900,0,yes,southwest,16884.92400
1,18,2,33.770,1,no,southeast,1725.55230
2,28,2,33.000,3,no,southeast,4449.46200
3,33,2,22.705,0,no,northwest,21984.47061
4,32,2,28.880,0,no,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,2,30.970,3,no,northwest,10600.54830
1334,18,1,31.920,0,no,northeast,2205.98080
1335,18,1,36.850,0,no,southeast,1629.83350
1336,21,1,25.800,0,no,southwest,2007.94500


In [15]:
df[['smoker']]

,smoker
0,yes
1,no
2,no
3,no
4,no
...,...
1333,no
1334,no
1335,no
1336,no


In [16]:
df['smoker'].unique()

<StringArray>
['yes', 'no']
Length: 2, dtype: str

In [17]:
df['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [18]:
smoker_dict={
    'yes':1, 'no':0
}

In [19]:
df['smoker']=df['smoker'].map(smoker_dict)

In [20]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,1,27.900,0,1,southwest,16884.92400
1,18,2,33.770,1,0,southeast,1725.55230
2,28,2,33.000,3,0,southeast,4449.46200
3,33,2,22.705,0,0,northwest,21984.47061
4,32,2,28.880,0,0,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,2,30.970,3,0,northwest,10600.54830
1334,18,1,31.920,0,0,northeast,2205.98080
1335,18,1,36.850,0,0,southeast,1629.83350
1336,21,1,25.800,0,0,southwest,2007.94500


In [21]:
df[['region']]

,region
0,southwest
1,southeast
2,southeast
3,northwest
4,northwest
...,...
1333,northwest
1334,northeast
1335,southeast
1336,southwest


In [22]:
df['region'].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [23]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [24]:
region_dict={
    'southwest':1, 'southeast':2, 'northwest':3, 'northeast':4
}

In [25]:
df['region']=df['region'].map(region_dict)

In [26]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,1,27.900,0,1,1,16884.92400
1,18,2,33.770,1,0,2,1725.55230
2,28,2,33.000,3,0,2,4449.46200
3,33,2,22.705,0,0,3,21984.47061
4,32,2,28.880,0,0,3,3866.85520
...,...,...,...,...,...,...,...
1333,50,2,30.970,3,0,3,10600.54830
1334,18,1,31.920,0,0,4,2205.98080
1335,18,1,36.850,0,0,2,1629.83350
1336,21,1,25.800,0,0,1,2007.94500


In [27]:
df.isnull().sum()

age         0
gender      0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(1)

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df.info()

<class 'pandas.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1337 non-null   int64  
 1   gender    1337 non-null   int64  
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64  
 4   smoker    1337 non-null   int64  
 5   region    1337 non-null   int64  
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(5)
memory usage: 83.6 KB


In [32]:
x=df.drop('charges',axis=1)

In [33]:
df

,age,gender,bmi,children,smoker,region,charges
0,19,1,27.900,0,1,1,16884.92400
1,18,2,33.770,1,0,2,1725.55230
2,28,2,33.000,3,0,2,4449.46200
3,33,2,22.705,0,0,3,21984.47061
4,32,2,28.880,0,0,3,3866.85520
...,...,...,...,...,...,...,...
1333,50,2,30.970,3,0,3,10600.54830
1334,18,1,31.920,0,0,4,2205.98080
1335,18,1,36.850,0,0,2,1629.83350
1336,21,1,25.800,0,0,1,2007.94500


In [34]:
x

,age,gender,bmi,children,smoker,region
0,19,1,27.900,0,1,1
1,18,2,33.770,1,0,2
2,28,2,33.000,3,0,2
3,33,2,22.705,0,0,3
4,32,2,28.880,0,0,3
...,...,...,...,...,...,...
1333,50,2,30.970,3,0,3
1334,18,1,31.920,0,0,4
1335,18,1,36.850,0,0,2
1336,21,1,25.800,0,0,1


In [35]:
y=df[['charges']]

In [36]:
y

,charges
0,16884.92400
1,1725.55230
2,4449.46200
3,21984.47061
4,3866.85520
...,...
1333,10600.54830
1334,2205.98080
1335,1629.83350
1336,2007.94500


In [37]:
# df.to_csv('clean_insurance_data.csv')

In [38]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [39]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [40]:
pip install Scikit-Learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [41]:
import sklearn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC,SVR
import joblib

In [42]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train ,y_test =train_test_split(x,y,test_size=0.2,random_state=42)


In [43]:
lr=LinearRegression()


In [44]:
lr.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [45]:
lr.score(x_train,y_train)

0.7297182858804965

In [46]:
lr.score(x_test,y_test)

0.8068466322629111

In [47]:
pred=lr.predict(x_test)

In [48]:
pred[0:10]

array([[ 8080.45018585],
       [ 5592.87111988],
       [14378.29865472],
       [31731.81954139],
       [ 9158.3569444 ],
       [13361.01426913],
       [30257.65525771],
       [ 1308.64735626],
       [10849.42544516],
       [11375.54851897]])

In [49]:
y_test[0:10]

,charges
900,8688.85885
1064,5708.86700
1256,11436.73815
298,38746.35510
237,4463.20510
481,9304.70190
240,38511.62830
277,2150.46900
415,7345.72660
707,10264.44210


In [50]:
# df.info()

In [51]:
joblib.dump(lr,"linear_model.lb")

['linear_model.lb']

In [52]:
model=joblib.load('linear_model.lb')

In [53]:
model.predict(x_test)

array([[ 8.08045019e+03],
       [ 5.59287112e+03],
       [ 1.43782987e+04],
       [ 3.17318195e+04],
       [ 9.15835694e+03],
       [ 1.33610143e+04],
       [ 3.02576553e+04],
       [ 1.30864736e+03],
       [ 1.08494254e+04],
       [ 1.13755485e+04],
       [ 1.04822214e+04],
       [ 3.31558608e+04],
       [ 3.09123841e+04],
       [ 1.71688443e+04],
       [ 1.06361393e+04],
       [ 9.37424715e+03],
       [ 3.96524338e+03],
       [ 3.19229863e+04],
       [ 3.08468457e+03],
       [ 5.47544373e+03],
       [ 3.76844305e+03],
       [ 3.01552667e+04],
       [ 1.50768984e+04],
       [ 3.02746510e+04],
       [ 3.10830548e+04],
       [ 5.52001772e+03],
       [ 3.56655758e+04],
       [ 3.63713163e+04],
       [ 1.12979802e+04],
       [ 1.40664742e+04],
       [ 6.37519963e+03],
       [ 1.29381095e+04],
       [ 6.79284837e+02],
       [ 1.19476924e+04],
       [ 3.97832706e+04],
       [ 1.21517558e+04],
       [ 4.57717842e+03],
       [ 4.01652351e+03],
       [ 3.1